### PR TITLE
Implementation of cheaper sort button for products

### PR DESCRIPTION
**Pull request by Are1205**

### CODE REVIEW

**Comment by avillota** [comment]
Code is working as expected and implemtns the sorting properly based on the price

**Comment by avillota** [comment]
Code is working as expected and implemtns the sorting properly based on the price

**Review by avillota — COMMENTED** [review]
Code is working as expected and implemtns the sorting properly based on the price

**Comment by vcalderonmol** [comment]
Implementation of cheaper sort button for products is working correctly

**Review by vcalderonmol — APPROVED** [review]

**Review by avillota — APPROVED** [review]
Code is working as expected and implemtns the sorting properly based on the price

**Pull request merged**
